name: Pochi Continuous Agent

on:
  workflow_dispatch:   # manual trigger for demo
  schedule:
    - cron: "0 0 * * *"    # nightly at midnight UTC

permissions:
  contents: write
  issues: write

jobs:
  nightly_todo_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan TODOs and create issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require("fs");
            const glob = require("glob");

            // find all source files
            const files = glob.sync("src/**/*.{ts,tsx,js,jsx}");

            for (const file of files) {
              const lines = fs.readFileSync(file, "utf-8").split("\n");
              lines.forEach((line, i) => {
                if (line.includes("TODO") || line.includes("FIXME")) {
                  const title = line.trim().slice(0, 60);
                  github.rest.issues.create({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    title: `TODO in ${file}:${i + 1}`,
                    body: `Found in \`${file}\` line ${i + 1}:\n\n${line.trim()}`
                  });
                }
              });
            }
