name: Pochi Auto Runner

on:
  workflow_run:
    workflows: ["Pochi Auto-Comments"]
    types:
      - completed

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  pochi_auto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Pochi
        uses: tabbyml/pochi/packages/github-action@main
        env:
          POCHI_API_KEY: ${{ secrets.POCHI_API_KEY }}
